# Generated by Django 5.0 on 2024-01-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
